import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Navbar } from "@/components/ui/layout/navbar/navbar";

const geistInter = Inter({
  variable: "--font-geist-inter",
  subsets: ["latin"],
});



export const metadata: Metadata = {
  title: "ShramBazar",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
     <body suppressHydrationWarning className={`${geistInter.variable} antialiased `}>
  
    <Navbar />
    {children}
  
</body>

    </html>
  );
}
